return {
  -- {
  --   "rmagatti/auto-session",
  --   config = function()
  --     require("auto-session").setup({
  --       log_level = "error",
  --       auto_session_suppress_dirs = { "~/", "~/Projects", "~/Downloads", "/" },
  --       auto_session_enabled = true,
  --       auto_save_enabled = true,
  --       auto_restore_enabled = false,
  --     })
  --   end,
  --   session_lens = {
  --     theme_conf = { border = true },
  --     previewer = true,
  --   },
  -- },
  -- {
  --   "telescope.nvim",
  --   dependencies = {
  --     "rmagatti/auto-session",
  --     build = "make",
  --     config = function()
  --       require("telescope").load_extension("session-lens")
  --     end,
  --   },
  -- },
}
